# Generated by Django 5.1.7 on 2025-03-08 14:23

import django.db.models.deletion
import profissoes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=profissoes.models.data)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profissoes', to='areas.area')),
            ],
        ),
    ]
